import { Play, Info } from 'lucide-react';
import { artwork, timeLabel } from '../api';
export default function HeroBanner({item, onPlay, onSelect}) {
  if (!item) return <section className="flex min-h-[55vh] items-center px-8 md:px-14"><div><p className="eyebrow">Make yourself at home</p><h1 className="mt-5 text-4xl font-bold md:text-6xl">Your next great story<br/>starts here.</h1><p className="mt-5 max-w-lg text-muted">Add media to your Jellyfin library, then return here to discover your movies, shows, and music.</p></div></section>;
  const image = artwork(item, true);
  return <section className="relative flex min-h-[620px] items-end overflow-hidden pb-24 pt-36 md:min-h-[680px]" aria-label="Featured title">
    {image && <img src={image} alt="" fetchPriority="high" className="absolute inset-0 h-full w-full object-cover object-top"/>}
    <div className="absolute inset-0 bg-gradient-to-r from-canvas via-canvas/65 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-canvas via-transparent to-canvas/25"/>
    <div className="relative z-10 max-w-2xl px-6 md:px-10 xl:px-14"><p className="eyebrow mb-5 flex items-center gap-3"><span className="h-px w-7 bg-accent"/>Tonight, made cinematic</p><h1 className="text-5xl font-bold leading-[1.04] tracking-tight md:text-7xl">{item.Name}</h1><div className="mt-5 flex flex-wrap items-center gap-3 text-xs font-medium text-slate-300">{item.CommunityRating > 0 && <span className="text-accent">★ {item.CommunityRating.toFixed(1)}</span>}<span>{item.ProductionYear}</span>{item.OfficialRating && <span className="rounded border border-white/30 px-1.5 py-.5">{item.OfficialRating}</span>}{item.RunTimeTicks && <span>{timeLabel(item.RunTimeTicks)}</span>}<span>{item.Genres?.slice(0, 2).join(' · ')}</span></div><p className="mt-5 line-clamp-3 max-w-lg text-sm leading-7 text-slate-300">{item.Overview}</p><div className="mt-7 flex flex-wrap gap-3"><button className="btn-primary min-w-36" onClick={() => item.IsFolder || item.Type === 'Series' ? onSelect(item) : onPlay(item)}><Play size={18} fill="currentColor"/>{item.IsFolder || item.Type === 'Series' ? 'Explore series' : item.UserData?.PlaybackPositionTicks ? 'Resume' : 'Play now'}</button><button className="btn-secondary" onClick={() => onSelect(item)}><Info size={18}/>More info</button></div></div>
    <div className="absolute bottom-16 right-14 hidden text-right text-[10px] uppercase tracking-[.2em] text-slate-400 lg:block">Your library.<br/><span className="mt-1 inline-block text-white">An extraordinary experience.</span></div>
  </section>;
}
