import { useState } from 'react';
import { LogOut, KeyRound, RefreshCw, Radio, Copy, Check } from 'lucide-react';
import { jf, post } from '../api';
export default function Settings({user, onLogout}) {
  const [token, setToken] = useState(''), [message, setMessage] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false), [users, setUsers] = useState([]), [selected, setSelected] = useState(null);
  async function run(fn, notice) {setBusy(true); setError(''); setMessage(''); try {await fn(); if (notice) setMessage(notice);} catch(e) {setError(e.message);} finally {setBusy(false);}}
  async function policy(event) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    await run(async () => {
      const fresh = await jf(`Users/${selected.Id}`);
      const value = {...fresh.Policy, IsDisabled: data.get('disabled') === 'on', EnableLiveTvAccess: data.get('livetv') === 'on', EnableLiveTvManagement: data.get('dvr') === 'on', MaxParentalRating: data.get('rating') === '' ? null : Number(data.get('rating'))};
      await post(`/jellyfin/Users/${selected.Id}/Policy`, value);
    }, 'User policy saved.');
  }
  return <div className="mx-auto max-w-4xl px-6 pb-14 pt-32 md:px-10"><p className="eyebrow">Make it yours</p><h1 className="mb-8 mt-3 text-4xl font-bold">Settings</h1>{error && <p role="alert" className="mb-5 rounded-lg bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}{message && <p role="status" className="mb-5 rounded-lg bg-accent/10 p-4 text-sm text-accent">{message}</p>}<section className="mb-6 rounded-xl border border-white/10 bg-surface p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xl font-semibold">{user.Name}</p><p className="mt-1 text-xs text-muted">{user.Policy?.IsAdministrator ? 'Administrator' : 'Personal profile'}</p></div><button className="btn-secondary" disabled={busy} onClick={() => run(async () => {await post('/auth/logout'); onLogout();})}><LogOut size={17}/>Switch user / Sign out</button></div><p className="mt-5 text-sm text-muted">Use the arrow keys to explore, Enter to select, and Escape to go back. Your watch history and library access follow your Jellyfin profile.</p></section>
    <section className="mb-6 rounded-xl border border-white/10 bg-surface p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><KeyRound size={19} className="text-accent"/>Connect your AI assistant</h2><p className="my-4 text-sm leading-6 text-muted">Let a compatible MCP client search your library and check what’s playing. Access follows your profile. Signing out revokes tokens created by this session.</p><label className="text-xs text-muted">SSE endpoint<input readOnly className="field mb-4 mt-2" value={window.location.origin + '/sse'}/></label><button className="btn-secondary" disabled={busy} onClick={() => run(async () => {const result = await post('/auth/mcp-token'); setToken(result.token); setCopied(false);})}>Create access token</button>{token && <div className="mt-5"><label className="text-xs text-muted">Bearer token<input readOnly type="password" className="field mt-2" value={token}/></label><button className="btn-secondary mt-3" onClick={() => run(async () => {await navigator.clipboard.writeText(token); setCopied(true);})}>{copied ? <Check size={16}/> : <Copy size={16}/>} {copied ? 'Copied' : 'Copy token'}</button></div>}</section>
    {user.Policy?.IsAdministrator && <><section className="mb-6 rounded-xl border border-white/10 bg-surface p-6"><h2 className="text-lg font-semibold">Server & live television</h2><p className="my-4 text-sm leading-6 text-muted">Scan your media folders for new arrivals or register the IPTV gateway configured on this server.</p><div className="flex flex-wrap gap-3"><button className="btn-secondary" disabled={busy} onClick={() => run(() => post('/jellyfin/Library/Refresh'), 'Library scan requested. New items will appear after Jellyfin finishes scanning.')}><RefreshCw size={16}/>Scan library</button><button className="btn-secondary" disabled={busy} onClick={() => run(() => post('/livetv/configure-iptv'), 'IPTV gateway registered. Refresh Live TV after guide ingestion completes.')}><Radio size={16}/>Connect IPTV gateway</button></div></section><section className="rounded-xl border border-white/10 bg-surface p-6"><h2 className="text-lg font-semibold">Profiles & parental controls</h2><p className="my-4 text-sm text-muted">Manage access using Jellyfin’s rating scale and per-user permissions.</p><button className="btn-secondary" disabled={busy} onClick={() => run(async () => setUsers(await jf('Users')))}>Manage profiles</button>{users.length > 0 && <label className="mt-5 block text-xs text-muted">Profile<select className="field mt-2" value={selected?.Id || ''} onChange={e => setSelected(users.find(u => u.Id === e.target.value) || null)}><option value="">Select a profile</option>{users.map(u => <option key={u.Id} value={u.Id}>{u.Name}</option>)}</select></label>}{selected && <form key={selected.Id} className="mt-5 space-y-4" onSubmit={policy}><label className="block text-sm">Maximum parental rating<input name="rating" type="number" min="0" max="1000" className="field mt-2" defaultValue={selected.Policy?.MaxParentalRating ?? ''} placeholder="Unrestricted"/></label><label className="flex gap-3 text-sm"><input type="checkbox" name="livetv" defaultChecked={selected.Policy?.EnableLiveTvAccess}/>Allow live TV</label><label className="flex gap-3 text-sm"><input type="checkbox" name="dvr" defaultChecked={selected.Policy?.EnableLiveTvManagement}/>Allow recording management</label><label className="flex gap-3 text-sm"><input type="checkbox" name="disabled" disabled={selected.Id === user.Id} defaultChecked={selected.Policy?.IsDisabled}/>Disable account</label><button className="btn-primary" disabled={busy}>Save policy</button></form>}</section></>}
  </div>;
}
